# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageVoting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageVoting
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    
    pod 'Alamofire'
    pod 'AlamofireImage'

    pod 'CodableFirebase'
    pod 'SCLAlertView'
    pod 'TransitionButton'
    pod 'NVActivityIndicatorView'

  target 'ImageVotingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
